@startuml
skinparam linetype polyline
scale 1000 width
state stop          <<stop>>

state Operational {
    idle            --> movingUp    : Order is received of a floor\nABOVE current floor
    idle            --> movingDown  : Order is received of a floor\nBELOW current floor

    Operational     --> stop        : Stop button is pressed
    stop            --> idle        : Stop button is released
    idle            --> loading     : Order is given at the current floor

    movingDown      --> loading : Arrival at\nordered floor
    movingUp        --> loading : Arrival at\nordered floor
    loading         --> idle    : Order completed

}

[*]             --> idle : Initializes elevator

@enduml
